steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/bank-ml-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/bank-ml-api:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bank-ml-api:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bank-ml-api:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'bank-ml-api',
      '--image', 'gcr.io/$PROJECT_ID/bank-ml-api:$COMMIT_SHA',
      '--region', 'asia-southeast2',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--timeout', '300',
      '--max-instances', '10',
      '--set-env-vars', 'ENVIRONMENT=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/bank-ml-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/bank-ml-api:latest'

# Optional: Specify build timeout (default is 10 minutes)
timeout: '1200s'

# Optional: Specify machine type for build
options:
  machineType: 'E2_HIGHCPU_8' 